### ISSUE TITLE
ImportError: Cannot initialize a headless EGL display / assert mdl is not None

### ISSUE THREAD

**Issue by KJW988** [mihdalal/planseqlearn#12]
```
AssertionError
[2024-11-01 14:28:28,619][absl][INFO] - MUJOCO_GL=egl, attempting to import specified OpenGL backend.
Error executing job with overrides: ['experiment_subdir=metaworld_psl_iclr_rerun', 'agent=drqv2', 'use_wandb=True', 'seed=15635468', 'debug=True', 'save_video=True', 'num_train_frames=2000000', 'eval_every_frames=20000', 'num_eval_episodes=10', 'wandb.project_name=psl', 'wandb.run_name=metaworld_psl_baseline_final_redo_006_metaworld_bin-picking-v2', 'task=metaworld_bin-picking-v2', 'psl=True', 'path_length=200', 'camera_name=gripperPOVpos', 'action_repeat=2', 'experiment_id=metaworld_psl_baseline_final_redo_006_metaworld_bin-picking-v2', 'replay_buffer_size=750000']
Traceback (most recent call last):
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "planseqlearn/train.py", line 34, in main
    from planseqlearn.environments.kitchen_dm_env import make_kitchen
  File "/workspace/Jiwon/planseqlearn/planseqlearn/environments/kitchen_dm_env.py", line 5, in <module>
    from dm_control.suite.wrappers import action_scale, pixels
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/suite/__init__.py", line 24, in <module>
    from dm_control.suite import acrobot
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/suite/acrobot.py", line 20, in <module>
    from dm_control import mujoco
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/mujoco/__init__.py", line 18, in <module>
    from dm_control.mujoco.engine import action_spec
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 41, in <module>
    from dm_control import _render
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/_render/__init__.py", line 86, in<module>
    Renderer = import_func()
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/_render/__init__.py", line 36, in_import_egl
    from dm_control._render.pyopengl.egl_renderer import EGLContext
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/_render/pyopengl/egl_renderer.py", line 75, in <module>
    raise ImportError('Cannot initialize a headless EGL display.')
ImportError: Cannot initialize a headless EGL display.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "planseqlearn/train.py", line 579, in <module>
    main()
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 251, in run_and_report
    assert mdl is not None
AssertionError
```

Dear Murtaza Dalal,
Thank you for providing such valuable research and code.

However, I encountered an error during the Model Training process while following the provided instructions. I have attached the error details above. I would greatly appreciate it if you could help me understand the nature of this error and suggest possible solutions. Despite attempting several fixes, I have not been able to resolve the issue.

Additionally, I noticed some warnings related to pip dependency conflicts while running ./install.sh. I suspect these warnings might be related to the problem, but I could not confirm this with certainty.

Thank you for your time and assistance.

Best regards,
Jiwon Kim

**Comment by Flxiang1** [comment]
> ```
> AssertionError
> [2024-11-01 14:28:28,619][absl][INFO] - MUJOCO_GL=egl, attempting to import specified OpenGL backend.
> Error executing job with overrides: ['experiment_subdir=metaworld_psl_iclr_rerun', 'agent=drqv2', 'use_wandb=True', 'seed=15635468', 'debug=True', 'save_video=True', 'num_train_frames=2000000', 'eval_every_frames=20000', 'num_eval_episodes=10', 'wandb.project_name=psl', 'wandb.run_name=metaworld_psl_baseline_final_redo_006_metaworld_bin-picking-v2', 'task=metaworld_bin-picking-v2', 'psl=True', 'path_length=200', 'camera_name=gripperPOVpos', 'action_repeat=2', 'experiment_id=metaworld_psl_baseline_final_redo_006_metaworld_bin-picking-v2', 'replay_buffer_size=750000']
> Traceback (most recent call last):
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
>     return func()
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
>     lambda: hydra.run(
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
>     _ = ret.return_value
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
>     raise self._return_value
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "planseqlearn/train.py", line 34, in main
>     from planseqlearn.environments.kitchen_dm_env import make_kitchen
>   File "/workspace/Jiwon/planseqlearn/planseqlearn/environments/kitchen_dm_env.py", line 5, in <module>
>     from dm_control.suite.wrappers import action_scale, pixels
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/suite/__init__.py", line 24, in <module>
>     from dm_control.suite import acrobot
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/suite/acrobot.py", line 20, in <module>
>     from dm_control import mujoco
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/mujoco/__init__.py", line 18, in <module>
>     from dm_control.mujoco.engine import action_spec
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 41, in <module>
>     from dm_control import _render
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/_render/__init__.py", line 86, in<module>
>     Renderer = import_func()
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/_render/__init__.py", line 36, in_import_egl
>     from dm_control._render.pyopengl.egl_renderer import EGLContext
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/dm_control/_render/pyopengl/egl_renderer.py", line 75, in <module>
>     raise ImportError('Cannot initialize a headless EGL display.')
> ImportError: Cannot initialize a headless EGL display.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "planseqlearn/train.py", line 579, in <module>
>     main()
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
>     _run_hydra(
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
>     run_and_report(
>   File "/opt/conda/envs/psl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 251, in run_and_report
>     assert mdl is not None
> AssertionError
> ```
> 
> Dear Murtaza Dalal, Thank you for providing such valuable research and code.
> 
> However, I encountered an error during the Model Training process while following the provided instructions. I have attached the error details above. I would greatly appreciate it if you could help me understand the nature of this error and suggest possible solutions. Despite attempting several fixes, I have not been able to resolve the issue.
> 
> Additionally, I noticed some warnings related to pip dependency conflicts while running ./install.sh. I suspect these warnings might be related to the problem, but I could not confirm this with certainty.
> 
> Thank you for your time and assistance.
> 
> Best regards, Jiwon Kim

Hi, how did you solve it?
