### ISSUE TITLE
Experiment detail (about GPU)

### ISSUE THREAD

**Issue by KJW988** [mihdalal/planseqlearn#13]
Could you let me know the details of the GPU used in the experiment, as well as the approximate time taken for both training and testing?

**Comment by mihdalal** [comment]
We ran all experiments on RTX 2080 Ti GPUs. Depending on the environment (rendering / dynamics speed varies by env and simulator), the training time could take up 1-4 days. Testing is quite quick, should not take more than a few minutes I think.

**Comment by KJW988** [comment]
Thank you for your response. Could you kindly confirm if the provided code fully implements what is demonstrated in the paper?

**Comment by mihdalal** [comment]
yes it should replicate the paper results
