### ISSUE TITLE
How were the figure images rendered

### ISSUE THREAD

**Issue by MandiZhao** [mihdalal/planseqlearn#4]
The renderings on the project website looks really good, a lot better than the other robosuite/metaworld figures I've seen. Just curious whether some external rendering engine was used. Thanks!

**Comment by mihdalal** [comment]
Thanks! Yes, I extended the NVISII rendering code that is present in robosuite (https://github.com/ARISE-Initiative/robosuite/tree/master/robosuite/renderers/nvisii) to support metaworld, d4rl kitchen, and obstructed suite. The basic idea is to just save the mujoco states from the video and then load them into NVISII and run ray-tracing based rendering. My code for doing this is very hacky and hardcoded, at the moment, but I might release a nicer version of it at some point. If you want my current version, shoot me an email and I can send it to you!

**Comment by MandiZhao** [comment]
Really cool, thanks!!
